name: html-build CI
on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout whatwg/html-build
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Shellcheck
      run: |
        shellcheck *.sh
        shellcheck ci-build/*.sh
    - name: Docker build
      run: ci-build/docker-build.sh
    - name: Checkout whatwg/html
      uses: actions/checkout@v3
      with:
        repository: whatwg/html
        path: html
        fetch-depth: 2
    - name: Test against whatwg/html
      run: |
        mkdir output
        bash ci-build/docker-run.sh "$GITHUB_WORKSPACE/html" output
    - name: Docker login
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker push
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: |
        docker tag "$REGISTRY/$IMAGE_NAME" "$REGISTRY/$IMAGE_NAME:$GITHUB_SHA"
        docker tag "$REGISTRY/$IMAGE_NAME" "$REGISTRY/$IMAGE_NAME:latest"
        docker push "$REGISTRY/$IMAGE_NAME:$GITHUB_SHA"
        docker push "$REGISTRY/$IMAGE_NAME:latest"
